SUCCESS in  benchmark_SEDC.py  AND DSNAME  20
PROCESS TOOK 900 SECONDS ERROR in  benchmark_SEDC.py  AND DSNAME  20 FOR C 0 AND ROW 1
