PROCESS TOOK 49 SECONDS ERROR in  benchmark_LORE.py  AND DSNAME  0 FOR C 0 AND ROW 1
SUCCESS in  benchmark_LORE.py  AND DSNAME  0
