PROCESS TOOK 5 SECONDS ERROR in  benchmark_SYNAS.py  AND DSNAME  15 FOR C 0 AND ROW 1
PROCESS TOOK 5 SECONDS ERROR in  benchmark_SYNAS.py  AND DSNAME  15 FOR C 0 AND ROW 0
