PROCESS TOOK 10 SECONDS SUCCESS in  benchmark_DiCE.py  AND DSNAME  18
PROCESS TOOK 10 SECONDS ERROR in  benchmark_DiCE.py  AND DSNAME  18 FOR C 1 AND ROW 0
